[FEAT] Add SoundPlay
DeveloperAcademy-POSTECH/MC2-Team12-EcoTales pull request #54
Opened 2022-06-14 02:48 UTC by yeahaluu

- AVFoundation을 사용한 사운드를 넣을 수 있는 함수입니다
- [Playing sound](https://www.hackingwithswift.com/forums/swiftui/playing-sound/4921) 해당 글을 참조했습니다
- 샘플 sound file: [mixkit](https://mixkit.co/free-sound-effects/game/)

함수는 다음과 같이 사용할 수 있습니다
```
ZStack {
    Text("Play Sound!")
}
.onAppear(perform: {
    playSounds("mixkit-player-jumping-in-a-video-game-2043.wav")
})
```

2022-06-14 03:14 UTC, eunbkang approved these changes

2022-06-14 04:01 UTC, taek0622 approved these changes
고생하셨습니다~

2022-06-14 04:01 UTC, glitterer approved these changes
너무 수고많으셨습니다

2022-06-14 04:01 UTC, glitterer commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +
p5
혹시 코드의 source 좀 알려주실 수 있나요~ 🥹

2022-06-14 04:02 UTC, Lim-YongKwan approved these changes
너무 고생 많으셨습니다!

2022-06-14 04:02 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +
위에 적혀 있습니다 ^0^

2022-06-14 05:50 UTC, Lia316 requested changes

2022-06-14 05:50 UTC, Lia316 commented on EcoTales/EcoTales/Screens/SoundTestView.swift
> +                .buttonStyle(PlainButtonStyle())
p2
modifier 줄바꿈 부탁드립니다~

2022-06-14 05:50 UTC, Lia316 commented on EcoTales/EcoTales/Screens/SoundTestView.swift
> +        }) {
p1
브랜치에 직접 접근해서 확인해봤는데, `playSound(sound:type:)` 함수가 구현된 부분이 보이지 않았습니다
PlaySound.swift 파일에 있는 함수는 `playSounds(_ soundFileName : String)`로 다른 것 같은데, 확인 부탁드립니다!

2022-06-14 05:50 UTC, Lia316 commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +}
p2

전역 변수 및, 전역 함수를 꼭 써야하는 상황인지 궁금합니다..!
지금 상태로는 모든 코드에서 `audioPlayer` 에 접근하여 플레이 할 수 있는데, 의도된 걸까요?

2022-06-14 05:50 UTC, Lia316 commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +    }
p1

[`fatalError`](https://developer.apple.com/documentation/swift/fatalerror(_:file:line:))는 메시지를 출력하고 앱 실행을 중단합니다.
이는 개발자가 인지하지 못하는 상황에서 예외처리하기 위함으로, 
앱이 죽지 않고 실행되는 것이 더 치명적인 버그를 생산할 때 쓴다고 합니다. [출처](https://dev200ok.blogspot.com/2020/06/swift-fatalerror.html)

저희 코드를 봤을 때, 음악 경로를 제대로 받지 못한다고 해서 앱이 죽을 필요는 없을 것 같다는 생각이 듭니다..!
오히려 앱이 중단되는 것이 사용자 경험을 저하하기 때문에 수정이 필요할 것 같습니다.

2022-06-14 05:53 UTC, yeahaluu commented on EcoTales/EcoTales/Screens/SoundTestView.swift
> +        }) {
SoundTestView 수정사항을 안 올렸습니다. 확인 감사합니다😍

2022-06-14 05:56 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +}
모든 코드에서 효과음 및 음악을 재생할 수 있는 가능성이 있다고 생각했습니다. 전역 변수와 전역 함수를 사용하지 않고, 모든 코드에 같은 코드를 복사하지 않으면서 음악을 재생할 수 있을까요?

2022-06-14 05:58 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +    }
수정하겠습니다. 감사합니다😊

2022-06-14 05:58 UTC, Lia316 commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +func playSounds(_ soundFileName : String) {
p3

`Colon Spacing Violation` 린트 규칙 준수 부탁드립니다~

2022-06-14 06:08 UTC, Lia316 commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +}
```swift
struct SoundManager {

    static func playSounds(_ soundFileName: String) {
        var audioPlayer: AVAudioPlayer!

        guard let soundURL = Bundle.main.url(forResource: soundFileName, withExtension: nil) else {
            print("Can't find sound file \(soundFileName)")
            return
        }
        do {
            audioPlayer = try AVAudioPlayer(contentsOf: soundURL)
        } catch {
            print(error.localizedDescription)
        }
        audioPlayer.play()
    }

}

SoundManager.playSounds("")
```

위의 코드 같이 구조체 안에 함수를 넣고도 static 메소드를 사용한다면 코드 중복을 피하면서 글로벌 변수 및 함수를 지양할 수 있지 않을까 싶습니다.

글로벌 변수와 정적 변수 모두 메모리에 상주해 있긴 하지만,
가독성, 변수의 관리 측면에서 차이점이 있다고 생각합니다.

예를 들면, `SoundManager.playSounds("")` 는 음악 재생 코드의 출처가 `SoundManager` 이라는 것을 바로 알 수 있지만, 
`playSounds("")` 의 경우, 내부 함수인지 헷갈립니다.
또한, 음악과 아예 관련이 없는 뷰도 `audioPlayer` 변수에 접근할 수 있는데, 
필요한 곳에서만 접근하는 것이 더 안전하고 의도가 명확하다고 생각합니다.

2022-06-14 06:18 UTC, Lia316 commented
@yeahaluu 수정 후 멘션 부탁드립니다!!

2022-06-15 02:41 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +}
우와 감사합니다 저렇게 바꿔보겠습니다❤️

2022-06-15 06:39 UTC, yeahaluu commented
@Lia316 고쳤습니다 확인부탁드립니다😊

2022-06-15 07:32 UTC, taek0622 approved these changes

2022-06-15 08:01 UTC, Lia316 requested changes
수고하셨습니다!

사실 셰리가 작성하신 코드는 셰리가 누구보다 더 잘 아실테니, 
리뷰어로서 제가 잘못 짚은 부분이 있다면 언제든지 말씀 부탁드립니다!!

2022-06-15 08:01 UTC, Lia316 commented on EcoTales/EcoTales/Screens/SoundTestView.swift
>          })
😄👍🏻👍🏻✨

2022-06-15 08:02 UTC, Lia316 commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +    }
저.. 생각해보니까 ㅋㅋㅋㅋ 
저번에 주석 처리한 린트 규칙을 부활시켜야하지 않나 하는 생각이 불현듯 스칩니다🤣

2022-06-16 03:00 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +struct SoundManager {
AVAudioPlayer 변수는 지역변수로 설정하먄 함수 실행 후 ARC에 의해 초기화 되어 실행이 되지 않는 것 처럼 행동합니다. 따라서 전역변수로 작성하였습니다.

2022-06-16 03:08 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +struct SoundManager {
리아의 피드백을 받아서 static에 넣었습니다 감사합니다❤️🙇‍♀️

2022-06-16 03:09 UTC, yeahaluu commented on EcoTales/EcoTales/Global/UIComponent/PlaySound.swift
> +        let soundURL = Bundle.main.url(forResource: soundFileName, withExtension: nil)
수정했습니다. 감사합니다!😊

2022-06-16 03:10 UTC, Lia316 commented
정말 수고하셨습니다!! 😆

2022-06-16 03:11 UTC, Lia316 approved these changes

2022-06-16 03:13 UTC, merged