게임에서 나올때 맵 팝업창 종료하기.
DeveloperAcademy-POSTECH/MC2-Team12-EcoTales pull request #58
Opened 2022-06-14 06:49 UTC by Lim-YongKwan

게임 내부 모달뷰에서 나올때 맵쪽 팝업창 종료하기 기능.

2022-06-15 00:47 UTC, glitterer approved these changes

2022-06-15 00:57 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Map/Views/Component/MapPopup/MapPopup.swift
>      @State var isGameStoryShow = false
p3;
`@State var isGameStoryShow`보다는 `@State private var isGameStoryShow`가 낫지 않을까요?

2022-06-15 01:48 UTC, eunbkang approved these changes

2022-06-15 07:35 UTC, taek0622 approved these changes

2022-06-15 13:19 UTC, Lia316 requested changes
다른 뷰에서도 코드를 수정하고 작성해야하는 어려움 등이 있으셨을 텐데
기능 구현을 잘 해주셔서 감사드립니다!

이번에도 변수명 및 주석에 대한 코멘트를 주로 달았습니다 😅
이해가 잘 가는 변수명을 찾는 그날까지 함께 달립시다!🏃🏻‍♀️

2022-06-15 13:19 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter1/Views/HiddenObjGameView.swift
>      var body: some View {
p2

`isStoryPopup` 이라는 변수명이 의도를 제대로 담고 있지 않아 어떤 역할을 하는지 헷갈립니다.💦
해당 변수는, 게임을 하는 도중에 멈추고 맵으로 돌아가거나, 다시 시작, 재개할 때 쓰는 팝업뷰를 띄워주기 위한 조건인데,
그러한 의미보다는 스토리 창이 팝업될 것 같은 느낌을 받습니다..!

2022-06-15 13:19 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter1/Views/HiddenObjGameView.swift
> -        HiddenObjGameView()
Q
이 부분은 아니지만,
77-82번째 줄 코드는 언제 쓰이는 함수인가요?

caller가 없어서 궁금함에 질문 드립니다!
혹시 그리즐리가 아니라 레인이 작성하신 코드일까요?? 👀

2022-06-15 13:19 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter1/Views/HiddenObjGameView.swift
> +    @State private var isStoryPopup = false
p3

`isMapPopup` 도 마찬가지로, 이름으로는 맵이 팝업! 될 느낌이 들지만,
사실 챕터1 숨그찾 게임 화면이 dismiss 되는 동작이라, 변수명이 적절하지 않다고 생각합니다

2022-06-15 13:19 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Map/Views/Component/MapPopup/MapPopup.swift
>      @State var isGameStoryShow = false
@taek0622 왜 해당 키워드를 사용해야하는지를 함께 설명해주시면서 제안해주신다면,
리뷰어도 빠르게 납득이 되고, 되묻는 시간을 줄일 수 있을 것 같습니다..!

제가 개인적으로 검색하실 키워드를 추천드리자면, `static dispatch`, `final`, `상속` 등이 있습니다
물론, 하나만 검색하시기 보다는, 함께 검색해야 자료가 나올 겁니다!

2022-06-15 13:19 UTC, Lia316 commented on EcoTales/EcoTales/Screens/EcoTalesApp.swift
> +            MapBackground()
p4

사용하지 않는 코드의 주석은 삭제 부탁드립니다..!

주석은 코드를 설명하기 위해 쓰는 것으로 용도를 제한하는 게 소통하기에 좋고,
코드 설명 주석도, 웬만하면 코드를 설명할 필요가 없이 짜는 것이 좋은 코드라고 개인적으로 생각합니다 🙂

2022-06-18 10:43 UTC, Lia316 commented
@Lim-YongKwan  변수명만큼은 수정되었으면 해서 기다리는 중입니다..!

혹시 이 부분에 대해 생각이 다른 부분이 있다면 말씀 부탁드립니다

2022-06-19 12:34 UTC, closed without merging