Ch4 panda game 구현
DeveloperAcademy-POSTECH/MC2-Team12-EcoTales pull request #81
Opened 2022-06-16 07:59 UTC by glitterer

- [x] 배경화면 추가
- [x] 일시정지 버튼 추가
- [x] 진짜 미뉴 버튼 추가
- [x] 버튼 액션 --> 성공 창 혹은 텍스트 띄우기
- [x] 성공창 띄웠을 때, 뒤에 dim 뜨게 만들기
- [x] 성공창이 뜨면 맞았다는 효과음
- [x] 틀린 미뉴들을 누르면 (i.e 진짜 메뉴를 제외한 나머지 창들을 누르면) 틀렸다는 효과음 추가
- [x] 미뉴 말고 다른 곳 누르면 소리 나오도록 처리

gif로 하면 소리가 안 들려서, 영상으로 올립니다

https://user-images.githubusercontent.com/50728605/174021335-de68a068-b71e-497f-93b2-914f3188d93b.mp4

2022-06-16 10:54 UTC, eunbkang approved these changes

2022-06-16 12:30 UTC, taek0622 reviewed
p1;
.DS_Store가 자꾸 트래킹 되는 것 같은데, ./EcoTales/.DS_Store 파일과 ./EcoTales/EcoTales/.DS_Store 파일 삭제 부탁드립니다.

2022-06-16 12:30 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter2/Views/Component/ChapterTwoLayout.swift
> +struct ChapterTwoLayout: View {
p2;
현재 `ChapterTwoLayout`이 챕터2의 메인뷰처럼 사용되고 있기 때문에 Layout이라는 명칭이 어울리지 않는 것 같습니다.
조금 더 직관적으로 명확하게 파악할 수 있는 이름으로 바꾸면 좋을 것 같아요.
또한, 메인 뷰이기 때문에 ./Views/Component 폴더 보다는 ./Views 폴더에 넣는 쪽이 더 좋을 것 같습니다.
항상 고생 많으십니다 :)

2022-06-16 12:43 UTC, Lim-YongKwan approved these changes
고생많으셨습니다!

2022-06-16 13:44 UTC, yeahaluu approved these changes
오즈짱!

2022-06-16 15:26 UTC, glitterer commented
> p1; .DS_Store가 자꾸 트래킹 되는 것 같은데, ./EcoTales/.DS_Store 파일과 ./EcoTales/EcoTales/.DS_Store 파일 삭제 부탁드립니다.

엄.. 어떻게 삭제 되는 것인지 모르겠지만.. 일단 `git pull origin main`을 통해서 merge conflict가 일어났을 때, main의 코드를 가져왔으니 괜찮아졌...지 않았을까 싶습니다 😅

2022-06-16 15:32 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter2/Views/Component/ChapterTwoLayout.swift
> +struct ChapterTwoLayout: View {
> 넵! 감사합니다~
> #72 에서 수정을 해서 merge를 했습니다.
> 그리고 현재의 branch에 `git pull origin main`을 통해서 merge conflict를 통해 처리했습니다!

넵! 감사합니다~
https://github.com/DeveloperAcademy-POSTECH/MC2-Team12-EcoTales/pull/72 에서 수정을 해서 merge를 했습니다.
그리고 현재의 branch에 git pull origin main을 통해서 merge conflict를 통해 처리했습니다!

2022-06-16 15:32 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter2/Views/Component/ChapterTwoLayout.swift
> +struct ChapterTwoLayout: View {
> p2; 현재 `ChapterTwoLayout`이 챕터2의 메인뷰처럼 사용되고 있기 때문에 Layout이라는 명칭이 어울리지 않는 것 같습니다. 조금 더 직관적으로 명확하게 파악할 수 있는 이름으로 바꾸면 좋을 것 같아요. 또한, 메인 뷰이기 때문에 ./Views/Component 폴더 보다는 ./Views 폴더에 넣는 쪽이 더 좋을 것 같습니다. 항상 고생 많으십니다 :)

넵! 감사합니다~
https://github.com/DeveloperAcademy-POSTECH/MC2-Team12-EcoTales/pull/72 에서 수정을 해서 merge를 했습니다.
그리고 현재의 branch에 git pull origin main을 통해서 merge conflict를 통해 처리했습니다!

2022-06-16 15:36 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter2/Views/Component/ChapterTwoLayout.swift
> +struct RecycleBins: View {
> 과거의 분리수거 게임도 들어왔군요!😣이건 지워야하지 않을까요?

맞습니다!
아마 #72 를 머지하기 전의 main을 pull했을 때의 branch로 작업을 해서 이렇게 되었던 것 같아요.
그래서 지금은 `git pull origin main`을 해당 branch로 하고, merge conflict 처리도 해서 업데이트 되었을 것으로 생각됩니다 :)

2022-06-18 11:44 UTC, Lia316 requested changes
오즈 정말 수고하셨습니다! 
소리 구현해보고 싶어하시더니 멋지게 성공하셨네요!! 🙌🏻

코멘트 대부분이 권고라, 꼭 수정해야할 사항은 거의 없긴 하지만, 
이미지 파일명 때문에 아이 이미지가 출력이 안 되는 것만 수정 부탁드립니다!

2022-06-18 11:44 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +    @State var audioPlayer: AVAudioPlayer!
p3

해당 변수는 사용되고 있지 않은 것 같습니다
삭제해도 괜찮을 것 같습니다 👀

2022-06-18 11:44 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                            .buttonStyle(PauseButtonStyle())
p4

라벨의 내용물이 없는 것이 이상해서 `PauseButtonStyle()`을 다시 봤더니,
버튼의 스타일이라기 보단, 버튼 라벨에 가까운 것 같더라고요..!
아예 `PauseButton`이나 `PauseButtonLabel`을 만드는 게 좋을 것 같다는 생각이 들었습니다.

2022-06-18 11:44 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                            .padding(.top, 5)
p2

현재 아이 캐릭터가 나오지 않고 있더라고요
메인으로 코드가 합쳐지고 코드를 가져오는 과정 중에 파일 명이 달라져서 그런 것 같습니다
파일명만 수정하면 잘 작동되어서, 파일명 수정 부탁드립니다!

2022-06-18 11:44 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                        SoundManager.playSounds("correctAnswer.mp3")
p4

`"character_meenuDoctor"`과 `"correctAnswer.mp3"` 같은 `String` 값은 `Literal` 로 넣는 것은 어떨까요?

2022-06-18 11:44 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                })
배경 이미지의 `onTapGesture` 로 틀렸을 때의 소리를 구현하고
클리어 이미지 `.onAppear(perform:_)` 로 맞을 때의 소리를 구현하신 것이 신기합니다! 배워가네요 😁👍🏻

2022-06-19 11:19 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                            .padding(.top, 5)
아! 이건 파일이 기존에 있는 아이의 파일이 아니라 다른 그림파일을 제가 추가시켰습니다! :)
그리고 새로 imageLiteral로도 수정했습니다~

2022-06-19 11:29 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                        SoundManager.playSounds("correctAnswer.mp3")
> p4
> 
> `"character_meenuDoctor"`과 `"correctAnswer.mp3"` 같은 `String` 값은 `Literal` 로 넣는 것은 어떨까요?

새로 SoundLiteral도 생성하고, ImageLiteral도 맞춰서 수정했습니다~

2022-06-19 11:35 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +    @State var audioPlayer: AVAudioPlayer!
> p3
> 
> 해당 변수는 사용되고 있지 않은 것 같습니다 삭제해도 괜찮을 것 같습니다 👀

오 sound파일들을 위해 사용해야하는 줄 알았는데 필요가 없었군요!
바로 반영했습니다~

2022-06-19 11:36 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                })
> 

칭찬 너무 감사합니다~ ^^
개인적으로는 무언가 하나라도 요소를 넣고 싶어서 넣어봤습니다..!
칭찬 받으니 기분이 좋습니다! 😁

2022-06-19 11:43 UTC, glitterer commented on EcoTales/EcoTales/Screens/Chapter4/PandaGameView.swift
> +                            .buttonStyle(PauseButtonStyle())
> p4
> 
> 라벨의 내용물이 없는 것이 이상해서 `PauseButtonStyle()`을 다시 봤더니, 버튼의 스타일이라기 보단, 버튼 라벨에 가까운 것 같더라고요..! 아예 `PauseButton`이나 `PauseButtonLabel`을 만드는 게 좋을 것 같다는 생각이 들었습니다.

해당코드는 일단 "일시정지"버튼인데 이 부분은 그리즐리의 코드에서 불러오는 코드인지라...
추후에 그리즐리의 새로 작성한 코드와 머지 후, 수정이 가능하다면 다시 보도록 하겠습니다~

2022-06-19 12:53 UTC, taek0622 approved these changes

2022-06-19 12:58 UTC, taek0622 approved these changes

2022-06-19 12:58 UTC, Lia316 approved these changes

2022-06-19 12:58 UTC, merged