틀린그림찾기 구현.
DeveloperAcademy-POSTECH/MC2-Team12-EcoTales pull request #87
Opened 2022-06-17 07:23 UTC by Lim-YongKwan

## 작업내용
- [ ] 틀린그림찾기 레이아웃 구현
- [ ] 일시정지 복붙
- [ ] 이미지 버튼 배치
- [ ] 터치 제스처 판단
- [ ] 오즈 멘트 정하기
- [ ] 틀리면 목숨 -1
- [ ] 3번 틀리면 game over 뜨기
- [ ] 맞으면 양쪽에 동그라미 뜨기
- [ ] 다 맞으면 게임 클리어 
- [ ] 맞을 때만 오즈 멘트 바꾸기

## 화면시연
![findWrongGif](https://user-images.githubusercontent.com/96565110/174247128-4647fa09-fea4-4334-8b31-293b97b13fa2.gif)

## 다음 할 일
- 숨은 그림찾기 다시 하기 구현
- 팝업 창 화면 변수 조정
- 숨은 그림찾기 멘트 구현

2022-06-17 15:38 UTC, yeahaluu approved these changes
고생하셨습니다 그리즐리 짱👍

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Global/UIComponent/StoryPopup/StoryPopup.swift
>                  ZStack(alignment: .center) {
질문;
여전히 ZStack 안에 ZStack이 바로 들어가야 하는 이유를 모르겠습니다.
이 부분에 대해서 설명이 필요해요.

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Global/UIComponent/StoryPopup/StoryPopup.swift
> +                    })
p2;
이 세 버튼은 왜 모양만 다르고 같은 기능을 하게 되었을까요?

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/Component/Chapter3StoryPopup.swift
> +struct Chapter3StoryPopup: View {
p2;
현재 파일 이름 및 struct 이름에 직접적으로 숫자가 들어가지 않습니다.
다른 파일 및 struct와 일관성 있게 이름 수정 부탁드립니다.

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/Component/Chapter3StoryPopup.swift
> +                ZStack(alignment: .center) {
p3;
마찬가지로 ZStack이 연달아 나와야 하는 근거가 부족합니다.
꼭 사용해야만 하는 명확한 이유가 없다면 수정이 필요해 보입니다.

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +class Chapter3UserSettings: ObservableObject {
p2;
현재 저희 프로젝트의 다른 파일 및 class들에서는 이름에 직접적으로 숫자가 들어간 경우가 없습니다. 다른 것들과 일관성 있게 이름 변경 부탁드립니다.

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                FindWrongScreenView( isFindWrongClear: $isFindWrongClear)
p2;
FindWrongScreenView 안의 파라미터 isFindWrongClear 앞에 필요없는 space가 들어갔습니다. 수정 부탁 드립니다.

2022-06-17 17:17 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                // Game Over
p2;
필요하지 않은 주석은 삭제 부탁드립니다.

2022-06-18 10:08 UTC, eunbkang approved these changes
수고하셨습니다~!

2022-06-18 14:01 UTC, Lia316 requested changes
로직 처리에 있어서 깔끔하다는 인상을 받았습니다! 👍🏻👍🏻

다만, 리뷰하는 입장에서 몇 가지 말씀드리고자 하는 것이 있습니다.
1. 협업 및 유지 보수를 위해 코드 가독성을 더 신경 써 주셨으면 합니다.
2. 해당 PR에는 여러가지 수정사항이 함께 있는 것 같습니다
  - 팝업창 연결
  - 틀린 그림 찾기 레이아웃
  - 틀린 그림 찾기 로직
  - 최대한 기능 단위로 PR을 분리해주시면, 리뷰하기 훨씬 수월하답니다 🙂
3. 유지 보수 및 확장성을 생각해서 enum을 적극 활용해주셨으면 합니다.
4. 현재 코드 구조 상, `EnvironmentObject`를 쓰는 것이 적절한 지 함께 고민해보고 싶습니다.

어디까지나 리뷰어의 개인적인 의견이지만 몇몇 부분은 적극적으로 고려해주셨으면 합니다.
수고하셨습니다!

2022-06-19 14:15 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .frame(width: 30, height: 30)
func에 묶어서 처리하고 싶었는데 실력이 부족해서 못하였습니다...

2022-06-19 14:15 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
컴포넌트화 너무 좋은데 이러한 부분에 대한 컴포넌트화를 지금 하기엔 남은 시간이 많지 않은데 가독성이 떨어지는 부분도 생길 수 있지 않을까요?
리아의 의견이 궁금합니다.

2022-06-19 14:15 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter1/Views/HiddenObjGameView.swift
> +    @Binding var isStoryPopup: Bool
우선 file private을 쓰는게 의미상으로는 더 알맞긴 한데 file private로 해도 밖으로 못 빼두는 점이 많이 아쉽네요...ㅠㅠ
우선 UpperPanelView 같은 경우에는 Chapter1, Chapter3에 중복되어서 쓰이지만 내부 구조가 달라서 private으로 썼습니다.

2022-06-19 14:15 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Global/UIComponent/StoryPopup/StoryPopup.swift
> +                    })
수정완료하였습니다.

2022-06-19 14:18 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +//
```Swift
@State var lifeCount: Int

var body:
```

2022-06-19 14:21 UTC, taek0622 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
p3;
modifier 줄 바꿔주세요

2022-06-19 14:22 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
`Dim()`  과 같이 이름을 따로 명시해준다면, 오히려 기능이 명확해서 가독성이 좋아지지 않을까 생각했습니다.

2022-06-19 14:28 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
opacity 줄 바꿨습니다!

2022-06-19 14:29 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
변수이름 때문에 혼선이 생기지 않을까 싶었는데 DimI()과 같은 이름이면 그러한 부분이 없겠네요! 좋은 의견 감사합니다!

2022-06-19 14:43 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +//
저도 일단 최첨단 수동으로 삭제해주고 있긴 합니다..
저번에 린트 규칙 찾아봤을 때는, 주석처리 할 수 없는 디폴트 규칙인 것 같아서 두고 있었습니다.

2022-06-19 17:05 UTC, Lia316 commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    }
아하 설명 감사드립니다! 😆

2022-06-19 17:05 UTC, Lim-YongKwan commented on EcoTales/EcoTales/Screens/Chapter3/Views/FindWrongGameView.swift
> +                    .ignoresSafeArea()
Dim() 스트럭트를 만들어서 해결하였습니다.
첨에는 extension으로 뺄려고 했는데 Color 쪽에 extension을 빼기에도 Image에 extension을 빼기에도 약간씩 맞물리지 않는 부분들이 생겨서 못하였습니다.
rectangle()등을 이용해서 화면을 꽉 채우면 가능할 것 같긴 한데 Color.black을 이용하는 방법으로는 struct 이상을 생각하지 못하여서 이러한 방식으로 짰습니다.
혹시 extension을 이용해서 `Color.dim()`을 하면 `Color.black.opacity(0.4).ignoresafeArea()`를 가능하게 하는 방법에 대해서 키워드 등이 있을까요?

2022-06-19 17:34 UTC, Lia316 approved these changes
코드 가독성이 많이 좋아져서 리뷰하기 좋아졌습니다! 감사합니다!
수고하셨습니다 🙌🏻
enum, EnvironmentObject 등의 권고 사항은 나중에 여유 되시면 한 번 생각해보시면 좋을 것 같아요!

2022-06-19 17:35 UTC, taek0622 approved these changes

2022-06-19 18:00 UTC, merged